# Generated by Django 2.2.12 on 2020-05-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='Type_of_paper',
            field=models.CharField(default='EndSem', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
