# Generated by Django 2.2.12 on 2020-05-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_auto_20200510_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdfbooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=50)),
                ('published_year', models.IntegerField(null=True)),
                ('pdf', models.FileField(upload_to='')),
            ],
        ),
    ]
