# Generated by Django 2.2.13 on 2020-06-23 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_remove_answer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='disliked',
            field=models.ManyToManyField(blank=True, related_name='answerdisliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='answerliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_like', to='Notes.Answer'),
        ),
    ]
