# Generated by Django 2.2.12 on 2020-05-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_pdfbooks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='batch',
        ),
        migrations.AlterField(
            model_name='pdfbooks',
            name='pdf',
            field=models.FileField(upload_to='#'),
        ),
    ]
