# Generated by Django 2.2.12 on 2020-05-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_auto_20200512_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='subject',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='papers',
            name='branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pdfbooks',
            name='subject',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='Branch',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Department',
            field=models.CharField(max_length=50),
        ),
    ]
