# Generated by Django 2.2.13 on 2020-07-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0005_auto_20200627_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
