# Generated by Django 2.2.12 on 2020-05-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0005_auto_20200512_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='owner_of_notes',
            new_name='Name',
        ),
    ]
