# Generated by Django 2.2.13 on 2020-07-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0006_auto_20200713_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(max_length=5000),
        ),
    ]
