# Generated by Django 2.2.12 on 2020-05-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0006_auto_20200513_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='Name',
            new_name='owner_of_notes',
        ),
    ]
