# Generated by Django 2.2.12 on 2020-05-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0008_auto_20200514_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='subject',
            field=models.CharField(choices=[('1', 'CSE'), ('2', 'IT'), ('3', 'EE'), ('4', 'Senior'), ('5', 'Graduate'), ('0', 'NOBRANCH')], default=0, max_length=10),
        ),
    ]
