# Generated by Django 2.2.12 on 2020-05-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0009_auto_20200516_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfbooks',
            name='branch',
            field=models.CharField(choices=[('1', 'CSE'), ('2', 'IT'), ('3', 'EE'), ('5', 'ECE'), ('6', 'ME'), ('7', 'CE'), ('8', 'CHA'), ('0', 'NOBRANCH')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='notes',
            name='branch',
            field=models.CharField(choices=[('1', 'CSE'), ('2', 'IT'), ('3', 'EE'), ('5', 'ECE'), ('6', 'ME'), ('7', 'CE'), ('8', 'CHA'), ('0', 'NOBRANCH')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='notes',
            name='subject',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notes',
            name='year',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], default=1),
        ),
        migrations.AlterField(
            model_name='papers',
            name='batch',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], default=1),
        ),
        migrations.AlterField(
            model_name='papers',
            name='branch',
            field=models.CharField(choices=[('1', 'CSE'), ('2', 'IT'), ('3', 'EE'), ('5', 'ECE'), ('6', 'ME'), ('7', 'CE'), ('8', 'CHA'), ('0', 'NOBRANCH')], default=0, max_length=10),
        ),
    ]
