# Generated by Django 2.2.12 on 2020-05-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0011_auto_20200516_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='Type_of_paper',
            field=models.CharField(choices=[(1, 'EndSem'), (2, 'ClassTest')], default='EndSem', max_length=10),
        ),
    ]
