# Generated by Django 2.2.12 on 2020-05-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0015_auto_20200516_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('EE', 'EE'), ('ECE', 'ECE'), ('ME', 'ME'), ('CE', 'CE'), ('CH', 'CH'), ('NOBRANCH', 'NOBRANCH')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='papers',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('EE', 'EE'), ('ECE', 'ECE'), ('ME', 'ME'), ('CE', 'CE'), ('CH', 'CH'), ('NOBRANCH', 'NOBRANCH')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='pdfbooks',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('EE', 'EE'), ('ECE', 'ECE'), ('ME', 'ME'), ('CE', 'CE'), ('CH', 'CH'), ('NOBRANCH', 'NOBRANCH')], default=0, max_length=10),
        ),
    ]
