# Generated by Django 2.2.12 on 2020-05-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0017_auto_20200516_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='owner_of_notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Notes.Student'),
        ),
    ]
