# Generated by Django 2.2.12 on 2020-05-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0019_auto_20200517_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Year',
            field=models.IntegerField(default=1),
        ),
    ]
