# Generated by Django 2.2.12 on 2020-05-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0020_auto_20200517_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='owner_of_notes',
        ),
    ]
