# Generated by Django 2.2.12 on 2020-05-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0021_remove_notes_owner_of_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
