# Generated by Django 2.2.12 on 2020-05-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0022_auto_20200517_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Branch',
            field=models.CharField(max_length=50),
        ),
    ]
