# Generated by Django 2.2.12 on 2020-05-18 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notes', '0023_auto_20200517_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default='tanu', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notes',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('EE', 'EE'), ('ECE', 'ECE'), ('ME', 'ME'), ('CE', 'CE'), ('CH', 'CH'), ('BTECH COMMON', 'BTECH COMMON')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='papers',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('EE', 'EE'), ('ECE', 'ECE'), ('ME', 'ME'), ('CE', 'CE'), ('CH', 'CH'), ('BTECH COMMON', 'BTECH COMMON')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='pdfbooks',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('EE', 'EE'), ('ECE', 'ECE'), ('ME', 'ME'), ('CE', 'CE'), ('CH', 'CH'), ('BTECH COMMON', 'BTECH COMMON')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='Branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('EE', 'EE'), ('ECE', 'ECE'), ('ME', 'ME'), ('CE', 'CE'), ('CH', 'CH'), ('BTECH COMMON', 'BTECH COMMON')], default='BTECH COMMON', max_length=20),
        ),
    ]
