# Generated by Django 2.2.12 on 2020-05-18 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notes', '0027_auto_20200518_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Year', models.IntegerField(default=1)),
                ('Branch', models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('EE', 'EE'), ('ECE', 'ECE'), ('ME', 'ME'), ('CE', 'CE'), ('CH', 'CH'), ('BTECH COMMON', 'BTECH COMMON')], default='BTECH COMMON', max_length=20)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
