# Generated by Django 2.2.12 on 2020-05-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0031_auto_20200518_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfbooks',
            name='year',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
        migrations.AlterField(
            model_name='pdfbooks',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('EE', 'EE'), ('ECE', 'ECE'), ('ME', 'ME'), ('CE', 'CE'), ('CH', 'CH'), ('BTECH COMMON', 'BTECH COMMON')], default='BTECH COMMON', max_length=20),
        ),
    ]
