# Generated by Django 2.2.12 on 2020-05-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0032_auto_20200519_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papers',
            old_name='batch',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='papers',
            name='data',
            field=models.FileField(upload_to='document/'),
        ),
        migrations.AlterField(
            model_name='pdfbooks',
            name='pdf',
            field=models.FileField(upload_to='document/'),
        ),
    ]
