# Generated by Django 2.2.12 on 2020-05-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0033_auto_20200520_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('EE', 'EE'), ('ECE', 'ECE'), ('ME', 'ME'), ('CE', 'CE'), ('CH', 'CH'), ('BTECH COMMON', 'BTECH COMMON')], max_length=20),
        ),
    ]
