# Generated by Django 2.2.12 on 2020-05-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0034_auto_20200520_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='year',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('Final', 'Final')], default='1st', max_length=10),
        ),
        migrations.AlterField(
            model_name='papers',
            name='Type_of_paper',
            field=models.CharField(choices=[('EndSem', 'EndSem'), ('ClassTest', 'ClassTest')], default='EndSem', max_length=10),
        ),
        migrations.AlterField(
            model_name='papers',
            name='year',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('Final', 'Final')], default='1st', max_length=10),
        ),
        migrations.AlterField(
            model_name='pdfbooks',
            name='year',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('Final', 'Final')], default='1st', max_length=10),
        ),
    ]
