# Generated by Django 2.2.12 on 2020-05-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0036_auto_20200528_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='liked',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
