# Generated by Django 2.2.12 on 2020-05-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0038_auto_20200528_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='upvote',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
