# Generated by Django 2.2.12 on 2020-05-28 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notes', '0039_auto_20200528_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.CharField(choices=[('upvote', 'upvote'), ('downvote', 'downvote')], default='upvote', max_length=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type', to='contenttypes.ContentType')),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_like', to='Notes.Notes')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers_like', to='Notes.Papers')),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_like', to='Notes.Pdfbooks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
