# Generated by Django 2.2.12 on 2020-05-28 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0040_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='like',
            name='object_id',
        ),
    ]
