# Generated by Django 2.2.12 on 2020-05-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0043_auto_20200528_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Year',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('Final', 'Final')], max_length=10),
        ),
    ]
