# Generated by Django 2.2.12 on 2020-05-29 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notes', '0045_auto_20200529_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfbooks',
            name='disliked',
            field=models.ManyToManyField(blank=True, related_name='pdfbooksdisliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pdfbooks',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='pdfbooksliked', to=settings.AUTH_USER_MODEL),
        ),
    ]
